
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('healthprofessional').del()
    .then(function () {
      // Inserts seed entries
      return knex('healthprofessional').insert([
        { username: 'Teste', 
          date: 19850112,
          email: 'teste@gmail.com',
          cpf: '123456789',
          telefone: '86985746321',
          password: '123456',
          sexo: 'masculino',
          cep: '65053390',
          logradouro: 'Rua Dez',
          cidade: 'São Luís',
          bairro: 'São Bernardo',
          numcasa: '903',
          profissao: 'medico',
          numregistro: '63524',
          especialidade: 'Cirurgia Geral',
          localidadedeatuacao: "Maranhão",
          deslocamentomax: "50"
        },
        { username: 'Raquel Luzia Jéssica Alves', 
          date: 19940224,
          email: 'raquelluziajessicaalves_@bds.com.br',
          cpf: '91594986509',
          telefone: '9129942576',
          password: '123456',
          sexo: 'feminino',
          cep: '67105150',
          logradouro: 'Rua da Prainha',
          cidade: 'Ananindeua',
          bairro: 'Marituba',
          numcasa: '350',
          profissao: 'medico',
          numregistro: '32561',
          especialidade: 'Pediatria',
          localidadedeatuacao: "pará",
          deslocamentomax: "44"
        },
        { username: 'Vanessa Mariana Aurora Martins', 
          date: 19430702,
          email: 'vvanessamarianaauroramartins@cpfl.com.br',
          cpf: '01883492009',
          telefone: '9485858545',
          password: '123456',
          sexo: 'feminino',
          cep: '33855200',
          logradouro: 'Rua Pouso Alegre',
          cidade: 'Ribeirão das Neves',
          bairro: 'Sevilha (1ª Seção)',
          numcasa: '857',
          profissao: 'enfermeiro',
          numregistro: '95862',
          especialidade: 'Pediatria',
          localidadedeatuacao: "Minas Gerais",
          deslocamentomax: "30"
        },
        { username: 'Isis Andrea Aparício', 
          date: 19660516,
          email: 'isisandreaaparicio_@stricker.eu.com',
          cpf: '29225193173',
          telefone: '65995970393',
          password: '123456',
          sexo: 'feminino',
          cep: '78065414',
          logradouro: 'Rua Holanda',
          cidade: 'Cuiabá',
          bairro: 'Jardim Europa',
          numcasa: '889',
          profissao: 'enfermeiro',
          numregistro: '14253',
          especialidade: 'Pediatria',
          localidadedeatuacao: "Mato Grosso",
          deslocamentomax: "20"
        },
        { username: 'Anderson Otávio Victor Ramos', 
          date: 19540601,
          email: 'andersonotaviovictorramos_@gruposandino.com.br',
          cpf: '46825088815',
          telefone: '7939483926',
          password: '123456',
          sexo: 'masculino',
          cep: '49097000',
          logradouro: 'Avenida São João Batista',
          cidade: 'Aracaju',
          bairro: 'Ponto Novo',
          numcasa: '775',
          profissao: 'enfermeiro',
          numregistro: '523423',
          especialidade: 'Pediatria',
          localidadedeatuacao: "Aracaju",
          deslocamentomax: "20"
        },
        { username: 'Flávia Sophia Antônia Baptista', 
          date: 19620601,
          email: 'flaviasophiaantoniabaptista@heindmec.com.br',
          cpf: '45545550119',
          telefone: '14985674253',
          password: '123456',
          sexo: 'feminino',
          cep: '78715758',
          logradouro: 'Rua Vinte',
          cidade: 'Rondonópolis',
          bairro: 'Jardim Liberdade',
          numcasa: '405',
          profissao: 'tecnicoEnfermagem',
          numregistro: '10236',
          especialidade: 'Pediatria',
          localidadedeatuacao: "Mato Grosso",
          deslocamentomax: "16"
        },
        { username: 'Ruan Cauã Nogueira', 
          date: 19440821,
          email: 'ruancauanogueiraruancauanogueira@gmailo.com',
          cpf: '96272157592',
          telefone: '68985746321',
          password: '123456',
          sexo: 'masculino',
          cep: '49092639',
          logradouro: 'Rua Quinze',
          cidade: 'Aracaju',
          bairro: 'Olaria',
          numcasa: '424',
          profissao: 'tecnicoEnfermagem',
          numregistro: '02154',
          especialidade: 'Pediatria',
          localidadedeatuacao: "Aracaju",
          deslocamentomax: "13"
        },
        { username: 'Nicole Sabrina Emilly Barbosa', 
          date: 19610423,
          email: 'nicolesabrinaemillybarbosa@yahoo.com',
          cpf: '59067396885',
          telefone: '63954862514',
          password: '123456',
          sexo: 'feminino',
          cep: '40270050',
          logradouro: 'Rua Rio Tocantins',
          cidade: 'Salvador',
          bairro: 'Vila Laura',
          numcasa: '557',
          profissao: 'fonoaudiologia',
          numregistro: '23221',
          especialidade: 'Pediatria',
          localidadedeatuacao: "Salvador",
          deslocamentomax: "51"
        },
        { username: 'Levi Raul da Luz', 
          date: 19440902,
          email: 'levirauldaluzlevirauldaluz@santarte.com',
          cpf: '87275348047',
          telefone: '24956987152',
          password: '123456',
          sexo: 'masculino',
          cep: '84345971',
          logradouro: 'Rua Principal, s/n',
          cidade: 'Ventania',
          bairro: 'Barro Preto',
          numcasa: '537',
          profissao: 'fonoaudiologia',
          numregistro: '67184',
          especialidade: 'clínica',
          localidadedeatuacao: "Paraná",
          deslocamentomax: "22"
        },
        { username: 'Danilo Lucas Pires', 
          date: 19560121,
          email: 'danilolucaspires-81@dep.ufscar.br',
          cpf: '31409253015',
          telefone: '2739600670',
          password: '123456',
          sexo: 'masculino',
          cep: '29160514',
          logradouro: 'Rua Rio Taquarí',
          cidade: 'Serra',
          bairro: 'Hélio Ferraz',
          numcasa: '541',
          profissao: 'nutricionista',
          numregistro: '46821',
          especialidade: 'clínica',
          localidadedeatuacao: "Espirito santo",
          deslocamentomax: "42"
        },
        { username: 'Agatha Carolina Nair Bernardes', 
          date: 19620307,
          email: 'agathacarolinanairbernardes@patriciagrillo.adv.br',
          cpf: '06566477365',
          telefone: '5138185128',
          password: '123456',
          sexo: 'feminino',
          cep: '90550002',
          logradouro: 'Avenida Benjamin Constant',
          cidade: 'Porto Alegre',
          bairro: 'São João',
          numcasa: '417',
          profissao: 'fisioterapeuta',
          numregistro: '2584',
          especialidade: 'Pediatria',
          localidadedeatuacao: "Rio de janeiro",
          deslocamentomax: "12"
        },
        { username: 'Isadora Aparecida Lara Silveira', 
          date: 19951023,
          email: 'isadoraaparecidalarasilveira-84@amordeconvite.com.br',
          cpf: '20198984898',
          telefone: '4528288814',
          password: '123456',
          sexo: 'feminino',
          cep: '85813187',
          logradouro: 'Rua Francisco Vaz de Lima',
          cidade: 'Cascavel',
          bairro: 'Brazmadeira',
          numcasa: '180',
          profissao: 'fisioterapeuta',
          numregistro: '7536',
          especialidade: '',
          localidadedeatuacao: "Pará",
          deslocamentomax: "20"
        },
        { username: 'Vitória Agatha Sônia Ramos', 
          date: 19910524,
          email: 'vitoriaagathasoniaramos@schon.com.br',
          cpf: '93285738820',
          telefone: '5329679259',
          password: '123456',
          sexo: 'feminino',
          cep: '96224120',
          logradouro: 'Rua Juvenal de Souza Freitas',
          cidade: 'Rio Grande',
          bairro: 'Povo Novo',
          numcasa: '488',
          profissao: 'medico',
          numregistro: '35648',
          especialidade: '',
          localidadedeatuacao: "Boa viagem",
          deslocamentomax: "41"
        },
        { username: 'Rosa Benedita Mendes', 
          date: 19970623,
          email: 'rosabeneditamendes@maggitoyota.com.br',
          cpf: '56074705801',
          telefone: '8229447619',
          password: '123456',
          sexo: 'feminino',
          cep: '57072310',
          logradouro: 'Rua Antônio Florêncio de Araújo Lima',
          cidade: 'Maceió',
          bairro: 'Cidade Universitária',
          numcasa: '780',
          profissao: 'fisioterapeuta',
          numregistro: '8598',
          especialidade: 'Gerontologia',
          localidadedeatuacao: "Maceió",
          deslocamentomax: "30"
        },
        { username: 'Aline Catarina Cláudia Rocha', 
          date: 20030313,
          email: 'alinecatarina@ntiequipamentos.com.br',
          cpf: '63177980608',
          telefone: '9529259763',
          password: '123456',
          sexo: 'feminino',
          cep: '69316396',
          logradouro: 'Avenida Nazaré Filgueiras',
          cidade: 'Boa Vista',
          bairro: 'Senador Hélio Campos',
          numcasa: '775',
          profissao: 'medico',
          numregistro: '53435',
          especialidade: 'Ginecologia',
          localidadedeatuacao: "Roraima",
          deslocamentomax: "12"
        },
      ]);
    });
};
